__title__ = 'datadots-api'
__description__ = 'Datadots API for Python'
__url__ = 'https://github.com/dotmesh-io/python-sdk'
__version__ = '0.1.2'
__author__ = 'Michael Hausenblas'
__author_email__ = 'michael.hausenblas@gmail.com'
__license__ = 'Apache 2.0'